name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.812
    - name: Restore dependencies
      run: dotnet restore
    - name: Get short SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Build
      run: dotnet build --no-restore -c Release --version-suffix "-${{ steps.vars.outputs.sha_short }}"
      
    - name: Upload nupkg as artifact
      uses: actions/upload-artifact@v2
      with:
        name: "${{ steps.vars.outputs.sha_short }}.nupkg"
        path: SubPixel.Instagram.SDK/bin/Release/*.nupkg

    - name: Upload dll as artifact
      uses: actions/upload-artifact@v2
      with:
        name: "SubPixel.Instagram.SDK-${{ steps.vars.outputs.sha_short }}.dll"
        path: SubPixel.Instagram.SDK/bin/Release/**/SubPixel.Instagram.SDK.dll
